In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data_for_test_10000 NEW.csv')

In [3]:
df.head()

,ID,Fullname,Birthday,Sex,Hometown,Jobtype,Salary,Marital Status
0,123456789012,Nguyen Van A,12/09/1985,Male,Tra Vinh,Software Engineer,15,Married
1,123456789013,Nguyen Van Anh,15/08/1990,Male,Quang Nam,Software Engineer,500,Married
2,123456789014,Nguyen Van Anh,20/07/1985,Female,Hung Yen,Architect,700,Married
3,123456789015,Tran Thi Minh Thu,12/05/1987,Female,Thanh pho Can Tho,Architect,200,Married
4,123456789016,Nguyen Van A,20/03/1990,Male,Ba Ria - Vung Tau,Architect,500,Single

In [4]:
print('Số hàng:', df.shape[0])
print('Số cột:', df.shape[1])

Số hàng: 9996
Số cột: 8

In [5]:
df.dtypes

ID                 int64
Fullname          object
Birthday          object
Sex               object
Hometown          object
Jobtype           object
Salary             int64
Marital Status    object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              9996 non-null   int64
 1   Fullname        9996 non-null   object
 2   Birthday        9996 non-null   object
 3   Sex             9996 non-null   object
 4   Hometown        9996 non-null   object
 5   Jobtype         9996 non-null   object
 6   Salary          9996 non-null   int64
 7   Marital Status  9996 non-null   object
dtypes: int64(2), object(6)
memory usage: 624.9+ KB

In [7]:
df.nunique()

ID                8365
Fullname           608
Birthday          2348
Sex                  2
Hometown            62
Jobtype            110
Salary             131
Marital Status       3
dtype: int64

In [8]:
df.select_dtypes(include = 'int64').corr()

              ID    Salary
ID      1.000000 -0.012712
Salary -0.012712  1.000000

In [9]:
def describe(data):

    categorical_columns = data.select_dtypes(include = 'object')

    count, unique, top, freq = [], [], [], []

    for i in categorical_columns:
        count.append(categorical_columns[i].count())
        unique.append(len(categorical_columns[i].unique()))
        top_value = categorical_columns[i].value_counts().idxmax()
        top.append(top_value)
        freq.append(categorical_columns[i].value_counts().max())

    describe_object = pd.DataFrame([count, unique, top, freq], columns = categorical_columns.columns, index = ['count', 'unique', 'top', 'freq'])

    numeric_columns = data.select_dtypes(include = 'int64')

    count, mean, std, min, onequarter, onehalf, threequarter, max  = [], [], [], [], [], [], [], []

    for i in numeric_columns:
        count.append(numeric_columns[i].count())
        mean.append(numeric_columns[i].mean())
        std.append(numeric_columns[i].std())
        min.append(numeric_columns[i].min())
        onequarter.append(numeric_columns[i].quantile(0.25))
        onehalf.append(numeric_columns[i].quantile(0.5))
        threequarter.append(numeric_columns[i].quantile(0.75))
        max.append(numeric_columns[i].max())

    describe_numeric = pd.DataFrame([count, mean, std, min, onequarter, onehalf, threequarter, max], columns = numeric_columns.columns, index = ['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'])

    return describe_numeric, describe_object

In [10]:
describe_numeric, describe_categorical = describe(df)

In [11]:
describe_numeric

                 ID        Salary
count  9.996000e+03   9996.000000
mean   2.263622e+11    242.270408
std    3.760361e+11    282.825436
min    1.234568e+09      5.000000
25%    1.234568e+11     20.000000
50%    1.234568e+11     45.000000
75%    1.234568e+11    500.000000
max    2.850319e+13  12345.000000

In [12]:
describe_categorical

,Fullname,Birthday,Sex,Hometown,Jobtype,Marital Status
count,9996,9996,9996,9996,9996,9996
unique,608,2348,2,62,110,3
top,Nguyen Van Anh,20/05/1990,Male,Thanh pho Can Tho,Software Engineer,Single
freq,2256,165,7259,340,4328,5142